f=open("file.txt","r")
print("using tell():")
print(f.tell())
print("reading the file:")
print(f.read())
f.seek(13)
print("using tell() after seek():")
print(f.tell())
print("reading the file after seek():")
print(f.read())
f.close()
print("using flush():")
f=open("file.txt","w")
f.write("hi gayathri!")
f.flush()
f.close()
print("reading the file after flush():")
f=open("file.txt","r")
print(f.read())
f.close()